apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: test
      mountPath: /data
    ports:
    - containerPort: 80
  volumes:
  - name: test
    flexVolume:
      driver: "azure/kv"
      options:
        volumeID: "vol1"
        size: "1000m"
        volumegroup: "kube_vg"
        resourceroup: "keyvaultflexvolume"